### PR TITLE
Add CI with cargo fmt and clippy

### PR DESCRIPTION
**Pull request by nullxDEADBEEF**
Add a GitHub Actions workflow that runs cargo fmt and clippy as to make sure our Rust code looks awesome.

### CODE REVIEW

**Comment by nullxDEADBEEF** [comment]
The CI works for now. Though it is annoying that cargo clippy has to download the project dependencies and check all of them. Cant seem to find any info on how to make clippy lint only our own code.

**Comment by AndreasPB** [comment]
Did fmt work in pre-commit?

We could do a mix of both, so we still get the benefit of fmt without having to wait for the CI to tell you that you're an idiot :DD

**Comment by nullxDEADBEEF** [comment]
None of them worked in pre-commit, since pre-commit doesn't have cargo installed. Sadly we need the CI to tell us we are being an idiot :D

**Review by AndreasPB — APPROVED** [review]

**Pull request merged**
